apiVersion: v1
kind: Service
metadata:
  name: node-emotion-listener
  labels:
    name: node-emotion-listener
spec:
  type: NodePort
  ports:
    - port: 3000        # Cluster IP http://10.109.199.234:3001
      targetPort: 3000  # Application port
      nodePort: 30000   # Example (EXTERNAL-IP VirtualBox IPs) http://192.168.50.11:30000/ 
      protocol: TCP
  selector:
     name: node-emotion-listener