apiVersion: v1
kind: Service
metadata:
  name: emotion-detect-api
  labels:
    name: emotion-detect-api
spec:
  type: ClusterIP
  ports:
  - port: 8501 #ClusterIP Port
    targetPort: 8501
    protocol: TCP

  selector:
    name: emotion-detect-api